apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: cloudru-namespace
spec:
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
