apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: cloudru-namespace
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
